apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: postgres:latest
              command:
                - "/bin/sh"
                - "-c"
                - "pg_dump -U admin -h postgresql -d mydatabase > {{ .Values.backup.backupDir }}/backup-$(date +\%F).sql"
              env:
                - name: PGPASSWORD
                  value: "password"
              volumeMounts:
                - name: backup-storage
                  mountPath: {{ .Values.backup.backupDir }}
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgresql-pvc
